// src/utils/auditTools.ts
import { escapeHtml } from './formatters';

export function saveReportToHistory(report: any) {
  try {
    const existingHistory = JSON.parse(localStorage.getItem('latsky_audit_history') || '[]');
    const newEntry = {
      id: Date.now(),
      reportId: report.id,
      reportPeriod: report.reportPeriod,
      date: new Date().toISOString(),
      clientName: report.clientName,
      reach: report.executiveSummary?.overallReach || 0,
      engagement: report.executiveSummary?.overallEngagementRate || 0,
      reportData: report
    };
    
    // Keep last 10 historical reports for MoM comparison
    // re-saving the same report replaces its previous entry instead of creating a duplicate
    const withoutDuplicate = existingHistory.filter((h: any) => !(report.id && h.reportId === report.id));
    const updated = [newEntry, ...withoutDuplicate].slice(0, 10);
    localStorage.setItem('latsky_audit_history', JSON.stringify(updated));
    return updated;
  } catch (e) {
    console.error('Failed to save audit history:', e);
    return [];
  }
}

export function calculateMoMDelta(currentReach: number, clientName?: string) {
  try {
    const all = JSON.parse(localStorage.getItem('latsky_audit_history') || '[]');
    // only compare a client with ITS OWN earlier report (history[0] is the report just saved)
    const history = clientName ? all.filter((h: any) => h.clientName === clientName) : all;
    if (history.length < 2) return { deltaPercent: 0, hasHistory: false };

    const previousReach = Number(history[1].reach);
    if (!Number.isFinite(previousReach) || previousReach <= 0) return { deltaPercent: 0, hasHistory: false };
    const deltaPercent = Number((((currentReach - previousReach) / previousReach) * 100).toFixed(1));
    return { deltaPercent, hasHistory: true };
  } catch {
    return { deltaPercent: 0, hasHistory: false };
  }
}

export function exportWhiteLabelPDF(report: any) {
  // Triggers browser print dialog formatted cleanly for professional executive PDF export
  try {
    const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8">
        <title>Social Audit Report - ${escapeHtml(report.clientName || 'Client')}</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #111; padding: 40px; line-height: 1.5; }
          h1 { color: #0f172a; margin-bottom: 4px; font-size: 26px; }
          .subtitle { color: #64748b; font-size: 13px; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 24px; font-weight: 600; }
          .metrics-grid { display: flex; gap: 16px; margin-bottom: 24px; flex-wrap: wrap; }
          .metric-box { background: #f8fafc; border: 1px solid #e2e8f0; padding: 16px; border-radius: 8px; flex: 1; min-width: 200px; }
          .metric-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #64748b; margin-bottom: 4px; }
          .metric-value { font-size: 22px; font-weight: bold; color: #0f172a; }
          .takeaways { background: #f0fdf4; border-left: 4px solid #22c55e; padding: 16px; margin-bottom: 24px; border-radius: 0 8px 8px 0; }
          .crisis-box { background: #fffbeb; border-left: 4px solid #f59e0b; padding: 16px; margin-bottom: 24px; border-radius: 0 8px 8px 0; }
          ul { padding-left: 20px; margin: 0; }
          li { margin-bottom: 8px; font-size: 13px; }
          h3 { font-size: 16px; color: #1e293b; margin-top: 24px; margin-bottom: 12px; }
          @media print {
            body { padding: 0; }
          }
        </style>
      </head>
      <body>
        <h1>${escapeHtml(report.clientName || 'Client Brand')}</h1>
        <div class="subtitle">Executive Social Media Audit & Intelligence Report • ${escapeHtml(report.reportPeriod || 'Current Period')}</div>
        
        <div class="metrics-grid">
          <div class="metric-box">
            <div class="metric-label">Total Reach (sum of platform figures, not de-duplicated)</div>
            <div class="metric-value">${(report.executiveSummary?.overallReach || 0).toLocaleString()}</div>
          </div>
          <div class="metric-box">
            <div class="metric-label">Reach-weighted Engagement Rate</div>
            <div class="metric-value">${report.executiveSummary?.overallEngagementRate || 0}%</div>
          </div>
        </div>

        <h3>Executive Takeaways</h3>
        <div class="takeaways">
          <ul>
            ${(report.executiveSummary?.headlineTakeaways || []).map((t: string) => `<li>${escapeHtml(t)}</li>`).join('')}
          </ul>
        </div>

        ${(report.crisisFixHooks && report.crisisFixHooks.length > 0) ? `
          <h3>Crisis-Fix Content Hooks (Generated by AI Audit)</h3>
          <div class="crisis-box">
            <ul>
              ${report.crisisFixHooks.map((h: any) => `<li><strong>[${escapeHtml(h.platform)}]</strong> <em>${escapeHtml(h.weaknessFound || '')}</em>: "${escapeHtml(h.hookSolution || '')}"</li>`).join('')}
            </ul>
          </div>
        ` : ''}

        <script>
          window.onload = function() {
            setTimeout(function() { window.print(); }, 200);
          };
        </script>
      </body>
    </html>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(htmlContent);
      printWindow.document.close();
      return true;
    }

    // Fallback if window.open is blocked by browser/iframe restrictions:
    const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${(report.clientName || 'Client').replace(/[^a-z0-9_-]/gi, '_')}_WhiteLabel_Audit_Report.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    return true;
  } catch (e) {
    console.error('Failed to export white-label PDF:', e);
    return false;
  }
}
